[project]
name = "conversion"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "h5py",
    "scipy",
    "tqdm",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["lifecycle-generation"]
